import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase, isSupabaseConfigured } from './supabaseClient';
import { Building2, LayoutDashboard, Users, WalletCards, BarChart3, Settings, HelpCircle, Search, Download, Plus, Eye, FileUp, MoreVertical, Printer, Filter, Grid2X2, List, X, Upload, Save, Trash2, Edit3, LogOut, ShieldCheck, LockKeyhole, Mail, Database, ServerCog, TrendingUp, TrendingDown, CalendarDays, CheckCircle2, Info, Landmark, BedDouble, ReceiptText, FileText, Home, DoorOpen, HandCoins, BadgeDollarSign } from 'lucide-react';
import './styles.css';

const modules = [
  ['dashboard', LayoutDashboard, 'Executive Dashboard'],
  ['companies', Building2, 'Companies'],
  ['contracts', FileText, 'Contracts'],
  ['camps', Home, 'Camps'],
  ['rooms', BedDouble, 'Rooms'],
  ['tenants', Users, 'Tenants'],
  ['allocations', DoorOpen, 'Allocations'],
  ['rent', HandCoins, 'Rent Collection'],
  ['expenses', ReceiptText, 'Expenses'],
  ['cheques', Landmark, 'Cheques'],
  ['settings', Settings, 'Settings'],
  ['support', HelpCircle, 'Support']
];
const tables = ['companies','contracts','camps','rooms','tenants','allocations','charges','payments','expenses','cheques','support_tickets'];
const today = () => new Date().toISOString().slice(0,10);
const money = n => `AED ${Number(n||0).toLocaleString('en-US',{maximumFractionDigits:2,minimumFractionDigits:Number(n||0)%1?2:0})}`;
const norm = v => String(v ?? '').toLowerCase();
const sum = (rows, k) => rows.reduce((a,r)=>a+Number(r[k]||0),0);
const csvDownload = (name, rows) => { const data=rows.length?rows:[{note:'No records'}]; const heads=Object.keys(data[0]); const csv=[heads.join(','),...data.map(r=>heads.map(h=>JSON.stringify(r[h]??'')).join(','))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download=name; a.click(); URL.revokeObjectURL(a.href); };
const filterRows = (rows, q, fields) => !q ? rows : rows.filter(r=>fields.some(f=>norm(r[f]).includes(norm(q))));
function dateObj(row,...keys){ const raw=keys.map(k=>row?.[k]).find(Boolean)||row?.created_at; const d=raw?new Date(raw):null; return d&&!isNaN(d)?d:null; }
function monthSum(rows, key, monthOffset=0, ...dateKeys){ const now=new Date(); const d=new Date(now.getFullYear(), now.getMonth()+monthOffset, 1); return rows.filter(r=>{ const x=dateObj(r,...dateKeys); return x&&x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth(); }).reduce((a,r)=>a+Number(r[key]||0),0); }
function trend(current, previous, suffix='from last month'){ if(!current&&!previous) return null; if(!previous) return 'New activity this month'; const pct=((current-previous)/previous)*100; return `${pct>=0?'+':''}${pct.toFixed(1)}% ${suffix}`; }
function trendTone(current, previous, lowerBetter=false){ if(!current&&!previous) return 'muted'; return (lowerBetter ? current<=previous : current>=previous) ? 'good' : 'danger'; }
function Toast({msg}){ return msg?<div className="toast">{msg}</div>:null; }
function Badge({children}){ return <span className={`badge ${norm(children).replaceAll(' ','-')}`}>{children||'—'}</span>; }
function Modal({title,onClose,children,wide}){ return <div className="overlay"><div className={`modal ${wide?'wide':''}`}><div className="modalHead"><h2>{title}</h2><button className="iconBtn" onClick={onClose}><X size={20}/></button></div>{children}</div></div>; }
function Field({label,children}){ return <label className="field"><span>{label}</span>{children}</label>; }
function Card({title,action,children}){ return <div className="card">{(title||action)&&<div className="cardHead"><h3>{title}</h3><div className="actions">{action}</div></div>}{children}</div>; }
function Title({title,sub}){ return <div className="title"><h1>{title}</h1><p>{sub}</p></div>; }
function Kpi({label,value,trendText,tone='good',helper,icon}){ return <div className="kpi">{icon&&<div className="kpiIcon">{icon}</div>}<small>{label}</small><h2>{value}</h2>{trendText&&<p className={`trend ${tone}`}>{tone==='danger'?<TrendingDown size={16}/>:<TrendingUp size={16}/>} {trendText}</p>}{helper&&<p className="helper"><Info size={15}/>{helper}</p>}</div>; }

function AuthScreen(){
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [err,setErr]=useState(''); const [loading,setLoading]=useState(false);
  async function login(e){ e.preventDefault(); if(!supabase) return; setErr(''); setLoading(true); const {error}=await supabase.auth.signInWithPassword({email,password}); setLoading(false); if(error) setErr(error.message); }
  return <div className="loginShell"><div className="loginPanel"><div className="loginHero"><Building2 size={44}/><p>Sarab Al Madina's Portal</p><h1>LaborConnect</h1><span>Enterprise camp, tenant, contract, rent, expense, cheque and allocation management.</span></div><form className="loginForm" onSubmit={login}><div className="secure"><ShieldCheck size={18}/> Authorized Access</div><h2>Sign in to workspace</h2>{!isSupabaseConfigured&&<div className="setup"><ServerCog size={18}/><span>Add database URL and public key in .env.</span></div>}<Field label="Email"><div className="inputIcon"><Mail size={18}/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/></div></Field><Field label="Password"><div className="inputIcon"><LockKeyhole size={18}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password"/></div></Field>{err&&<p className="error">{err}</p>}<button className="primary" disabled={loading||!isSupabaseConfigured}>{loading?'Signing in...':'Login to ERP'}</button><footer><Database size={15}/> Sarab Data powered</footer></form></div></div>;
}

function App(){
  const [session,setSession]=useState(null); const [loading,setLoading]=useState(true); const [page,setPage]=useState('dashboard'); const [query,setQuery]=useState(''); const [modal,setModal]=useState(null); const [toast,setToast]=useState('');
  const [data,setData]=useState(Object.fromEntries(tables.map(t=>[t,[]])));
  const showToast = m => { setToast(m); setTimeout(()=>setToast(''),2400); };
  useEffect(()=>{ if(!supabase){setLoading(false);return;} supabase.auth.getSession().then(({data})=>{setSession(data.session); setLoading(false);}); const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>sub.subscription.unsubscribe(); },[]);
  useEffect(()=>{ if(session) loadAll(); },[session]);
  async function loadAll(){ setLoading(true); const results=await Promise.all(tables.map(t=>supabase.from(t).select('*').order('created_at',{ascending:false}))); setData(Object.fromEntries(tables.map((t,i)=>[t,results[i].data||[]]))); setLoading(false); }
  async function insert(table,payload){ const {error}=await supabase.from(table).insert(payload); if(error) return showToast(error.message); await loadAll(); setModal(null); showToast('Saved successfully'); }
  async function update(table,id,payload){ const {error}=await supabase.from(table).update(payload).eq('id',id); if(error) return showToast(error.message); await loadAll(); setModal(null); showToast('Updated successfully'); }
  async function remove(table,id){ if(!confirm('Delete this record?')) return; const {error}=await supabase.from(table).delete().eq('id',id); if(error) return showToast(error.message); await loadAll(); showToast('Deleted'); }
  if(loading) return <div className="loader">Loading LaborConnect...</div>;
  if(!session) return <AuthScreen/>;
  async function importRecords(table, rows){ const cleaned=cleanImportRows(table,rows); if(!table) return showToast('Import not available on this page'); if(!cleaned.length) return showToast('No rows found in CSV'); const {error}=await supabase.from(table).insert(cleaned); if(error) return showToast(error.message); await loadAll(); setModal(null); showToast(`Imported ${cleaned.length} rows`); }
  async function deleteCurrentPage(){ const ts=getPageTables(page); if(!ts.length) return showToast('No data table on this page'); if(!confirm(`Delete all data for ${modules.find(m=>m[0]===page)?.[2]}? This cannot be undone.`)) return; for(const t of ts){ const ids=(data[t]||[]).map(r=>r.id).filter(Boolean); if(ids.length){ const {error}=await supabase.from(t).delete().in('id',ids); if(error) return showToast(error.message); }} await loadAll(); showToast('Data deleted'); }
  const ctx={data,query,setModal,insert,update,remove,loadAll,showToast,setPage,importRecords,deleteCurrentPage,page};
  const exportRows = getExportRows(page,data,query);
  return <div className="app"><aside><div className="brand"><h1>LaborConnect</h1><p>Sarab Al Madina's Portal</p></div><nav>{modules.map(([key,Icon,label])=><button key={key} onClick={()=>setPage(key)} className={page===key?'active':''}><Icon size={18}/>{label}</button>)}</nav><div className="user"><div>A</div><span><b>Asama Ashraf</b><small>Manager</small></span><button onClick={()=>supabase.auth.signOut()} title="Logout"><LogOut size={16}/></button></div></aside><main><header><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search across enterprise..."/></div><h2>{modules.find(m=>m[0]===page)?.[2]}</h2><button className="secondary" onClick={()=>setModal({type:'import',page,table:getPrimaryTable(page)})}><Upload size={16}/> Import</button><button className="secondary" onClick={()=>csvDownload(`${page}.csv`,exportRows)}><Download size={16}/> Export</button><button className="dangerBtn" onClick={deleteCurrentPage}><Trash2 size={16}/> Delete Data</button><button className="primary" onClick={()=>setModal({type:defaultModal(page)})}><Plus size={16}/> New</button></header><Content page={page} ctx={ctx}/></main>{modal&&<DynamicModal modal={modal} ctx={ctx} close={()=>setModal(null)}/>}<Toast msg={toast}/></div>;
}
function defaultModal(page){ return ({companies:'company',contracts:'contract',camps:'camp',rooms:'room',tenants:'tenant',allocations:'allocation',rent:'charge',expenses:'expense',cheques:'cheque',support:'ticket'})[page] || 'company'; }
function Content({page,ctx}){ const map={dashboard:Dashboard,companies:Companies,contracts:Contracts,camps:Camps,rooms:Rooms,tenants:Tenants,allocations:Allocations,rent:Rent,expenses:Expenses,cheques:Cheques,settings:SettingsPage,support:Support}; const C=map[page]||Dashboard; return <C ctx={ctx}/>; }
function getExportRows(page,d,q){ const x={companies:d.companies,contracts:d.contracts,camps:d.camps,rooms:d.rooms,tenants:d.tenants,allocations:d.allocations,rent:[...d.charges,...d.payments],expenses:d.expenses,cheques:d.cheques,support:d.support_tickets}[page]||[]; return x; }
function getPageTables(page){ return ({companies:['companies'],contracts:['contracts'],camps:['camps'],rooms:['rooms'],tenants:['tenants'],allocations:['allocations'],rent:['charges','payments'],expenses:['expenses'],cheques:['cheques'],support:['support_tickets']})[page]||[]; }
function getPrimaryTable(page){ return ({companies:'companies',contracts:'contracts',camps:'camps',rooms:'rooms',tenants:'tenants',allocations:'allocations',rent:'charges',expenses:'expenses',cheques:'cheques',support:'support_tickets'})[page]||null; }
function parseCsv(text){
  const rows=[]; let row=[], cur='', quote=false;
  for(let i=0;i<text.length;i++){
    const ch=text[i], nx=text[i+1];
    if(ch==='"' && quote && nx==='"'){ cur+='"'; i++; continue; }
    if(ch==='"'){ quote=!quote; continue; }
    if(ch===',' && !quote){ row.push(cur.trim()); cur=''; continue; }
    if((ch==='\n'||ch==='\r') && !quote){ if(ch==='\r'&&nx==='\n') i++; row.push(cur.trim()); if(row.some(v=>v!=='')) rows.push(row); row=[]; cur=''; continue; }
    cur+=ch;
  }
  row.push(cur.trim()); if(row.some(v=>v!=='')) rows.push(row);
  if(rows.length<2) return [];
  const headers=rows[0].map(h=>h.trim()).filter(Boolean);
  return rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??'']))).filter(o=>Object.values(o).some(Boolean));
}
function cleanImportRows(table, rows){
  const blocked=['id','created_at','balance'];
  return rows.map(r=>Object.fromEntries(Object.entries(r).filter(([k,v])=>!blocked.includes(k)&&v!==''))).map(r=>{
    ['rooms','capacity','maintenance_count','occupied','monthly_rent','security_deposit','amount_due','amount_paid','amount','balance'].forEach(k=>{ if(k in r) r[k]=Number(r[k]||0); });
    ['docs_complete'].forEach(k=>{ if(k in r) r[k]=String(r[k]).toLowerCase()==='true'||String(r[k])==='1'||String(r[k]).toLowerCase()==='yes'; });
    return r;
  });
}


function Dashboard({ctx}){ const d=ctx.data; const activeTenants=d.tenants.filter(t=>t.status==='Active').length; const capacity=sum(d.camps,'capacity'); const occupied=Math.min(activeTenants,capacity); const vacant=Math.max(capacity-occupied-sum(d.camps,'maintenance_count'),0); const collected=sum(d.payments,'amount'); const expenses=sum(d.expenses,'amount'); const outstanding=sum(d.charges,'balance'); const thisColl=monthSum(d.payments,'amount',0,'payment_date'); const lastColl=monthSum(d.payments,'amount',-1,'payment_date'); const thisExp=monthSum(d.expenses,'amount',0,'expense_date'); const lastExp=monthSum(d.expenses,'amount',-1,'expense_date'); return <section><div className="heroTitle"><Title title="Executive Dashboard" sub="Live ERP overview for companies, camps, tenants, contracts, collections and expenses."/><button onClick={()=>ctx.setModal({type:'company'})} className="primary"><Plus size={16}/> New Asset</button></div><div className="kpiGrid"><Kpi label="Total Collection" value={money(collected)} trendText={trend(thisColl,lastColl)} tone={trendTone(thisColl,lastColl)} icon={<HandCoins/>}/><Kpi label="Total Expenses" value={money(expenses)} trendText={trend(thisExp,lastExp,'vs last month')} tone={trendTone(thisExp,lastExp,true)} icon={<ReceiptText/>}/><Kpi label="Net Profit" value={money(collected-expenses)} icon={<BadgeDollarSign/>}/><Kpi label="Outstanding" value={money(outstanding)} helper="Open balances from rent/WiFi/other dues" icon={<WalletCards/>}/></div><div className="dashGrid"><Card title="Collection vs Expense Trend"><Bars payments={d.payments} expenses={d.expenses}/></Card><Card title="Occupancy Analytics"><Occupancy occupied={occupied} vacant={vacant} maintenance={sum(d.camps,'maintenance_count')} total={capacity}/></Card></div><Card title="Recent Activity" action={<button className="ghost" onClick={()=>ctx.setPage('rent')}>View collections</button>}><Activity data={d}/></Card></section>; }
function Bars({payments,expenses}){ const months=[...Array(6)].map((_,i)=>{const date=new Date(); date.setMonth(date.getMonth()-5+i); return {m:date.getMonth(), y:date.getFullYear(), label:date.toLocaleString('en-US',{month:'short'})};}); const rows=months.map(x=>({label:x.label,c:payments.filter(p=>{const d=dateObj(p,'payment_date'); return d&&d.getMonth()===x.m&&d.getFullYear()===x.y}).reduce((a,p)=>a+Number(p.amount||0),0), e:expenses.filter(p=>{const d=dateObj(p,'expense_date'); return d&&d.getMonth()===x.m&&d.getFullYear()===x.y}).reduce((a,p)=>a+Number(p.amount||0),0)})); const max=Math.max(...rows.flatMap(r=>[r.c,r.e]),1); if(rows.every(r=>!r.c&&!r.e)) return <Empty title="No collection or expense data yet" text="Record payments and log expenses to build this trend."/>; return <div className="bars">{rows.map(r=><div key={r.label}><i style={{height:`${Math.max(8,r.c/max*150)}px`}}/><em style={{height:`${Math.max(8,r.e/max*150)}px`}}/><span>{r.label}</span></div>)}</div>; }
function Occupancy({occupied,vacant,maintenance,total}){ const pct=total?Math.round(occupied/total*100):0; const g=total?`conic-gradient(#006c49 0 ${pct*3.6}deg,#d9e2ef ${pct*3.6}deg ${(pct+(vacant/total*100))*3.6}deg,#ba1a1a 0)`: '#edf2f7'; return <div className="occupancy"><div className="donut" style={{background:g}}><div><b>{pct}%</b><span>Occupied</span></div></div><div className="occRows"><p><i className="green"/>Occupied<b>{occupied}</b></p><p><i/>Vacant<b>{vacant}</b></p><p><i className="red"/>Maintenance<b>{maintenance}</b></p></div>{!total&&<Empty title="No camp capacity yet" text="Add camps and rooms to activate occupancy."/>}</div>; }
function Activity({data}){ const rows=[...data.payments.map(p=>({t:'Payment',name:p.tenant_name,amount:money(p.amount),date:p.payment_date})),...data.expenses.map(e=>({t:'Expense',name:e.vendor,amount:money(e.amount),date:e.expense_date})),...data.tenants.map(t=>({t:'Tenant',name:t.name,amount:t.status,date:t.check_in_date}))].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8); if(!rows.length) return <Empty title="No activity yet" text="Start by adding companies, camps, tenants, dues, and expenses."/>; return <Table cols={['Type','Name','Value','Date']} rows={rows.map(r=>[r.t,r.name,r.amount,r.date])}/>; }

function Companies({ctx}){ const rows=filterRows(ctx.data.companies,ctx.query,['name','contact_name','phone','email','status']); return <Directory title="Company Directory" sub="Manage client companies and billing relationships." rows={rows} cols={['Company','Contact','Phone','Status','Balance']} render={c=>[<b>{c.name}</b>,c.contact_name||c.email,c.phone,<Badge>{c.status}</Badge>,money(c.balance)]} onAdd={()=>ctx.setModal({type:'company'})} onView={c=>ctx.setModal({type:'companyView',item:c})} onEdit={c=>ctx.setModal({type:'company',item:c})} onDelete={c=>ctx.remove('companies',c.id)}/>; }
function Contracts({ctx}){ const rows=filterRows(ctx.data.contracts,ctx.query,['contract_no','company','camp_name','status']); return <Directory title="Contract Management" sub="Track active, expiring, and renewed accommodation contracts." rows={rows} cols={['Contract','Company','Camp','Dates','Monthly Rent','Status']} render={r=>[r.contract_no||'—',r.company,r.camp_name,`${r.start_date||'—'} → ${r.end_date||'—'}`,money(r.monthly_rent),<Badge>{r.status}</Badge>]} onAdd={()=>ctx.setModal({type:'contract'})} onView={r=>ctx.setModal({type:'contractView',item:r})} onEdit={r=>ctx.setModal({type:'contract',item:r})} onDelete={r=>ctx.remove('contracts',r.id)}/>; }
function Camps({ctx}){ const rows=filterRows(ctx.data.camps,ctx.query,['name','location','emirate','status']); return <Directory title="Camp Directory" sub="Residential camp master records, capacity and operational status." rows={rows} cols={['Camp','Location','Rooms','Capacity','Maintenance','Status']} render={c=>[<b>{c.name}</b>,`${c.location||''} ${c.emirate||''}`,c.rooms,c.capacity,c.maintenance_count,<Badge>{c.status}</Badge>]} onAdd={()=>ctx.setModal({type:'camp'})} onEdit={c=>ctx.setModal({type:'camp',item:c})} onDelete={c=>ctx.remove('camps',c.id)}/>; }
function Rooms({ctx}){ const rows=filterRows(ctx.data.rooms,ctx.query,['room_no','camp_name','status']); return <Directory title="Room Directory" sub="Room inventory, capacity and occupancy management." rows={rows} cols={['Room','Camp','Floor','Capacity','Occupied','Status']} render={r=>[<b>{r.room_no}</b>,r.camp_name,r.floor,r.capacity,r.occupied,<Badge>{r.status}</Badge>]} onAdd={()=>ctx.setModal({type:'room'})} onEdit={r=>ctx.setModal({type:'room',item:r})} onDelete={r=>ctx.remove('rooms',r.id)}/>; }
function Tenants({ctx}){ const rows=filterRows(ctx.data.tenants,ctx.query,['name','company','emirates_id','room','camp_name','status']); return <Directory title="Tenant Directory" sub="Tenant registry, documents, room and company allocation." rows={rows} cols={['Tenant','Company','Room / Camp','Emirates ID','Lease End','Status']} render={t=>[<b>{t.name}</b>,t.company,`${t.room||'—'} / ${t.camp_name||'—'}`,t.emirates_id,t.lease_end_date,<Badge>{t.status}</Badge>]} onAdd={()=>ctx.setModal({type:'tenant'})} onView={t=>ctx.setModal({type:'tenantView',item:t})} onEdit={t=>ctx.setModal({type:'tenant',item:t})} onDelete={t=>ctx.remove('tenants',t.id)}/>; }
function Allocations({ctx}){ const rows=filterRows(ctx.data.allocations,ctx.query,['tenant_name','company','camp_name','room','status']); return <Directory title="Room Allocation" sub="Assign tenants to camps and rooms, then track checkout status." rows={rows} cols={['Tenant','Company','Camp','Room','Date','Status']} render={a=>[a.tenant_name,a.company,a.camp_name,a.room,a.allocation_date,<Badge>{a.status}</Badge>]} onAdd={()=>ctx.setModal({type:'allocation'})} onEdit={a=>ctx.setModal({type:'allocation',item:a})} onDelete={a=>ctx.remove('allocations',a.id)}/>; }
function Rent({ctx}){ const charges=filterRows(ctx.data.charges,ctx.query,['tenant_name','company','charge_type','status','receipt_no']); const payments=filterRows(ctx.data.payments,ctx.query,['tenant_name','company','receipt_no','method']); const outstanding=sum(charges,'balance'); const paidToday=ctx.data.payments.filter(p=>p.payment_date===today()).reduce((a,p)=>a+Number(p.amount||0),0); return <section><div className="heroTitle"><Title title="Rent Collection Overview" sub="Create dues first, then record rent/WiFi/other collections against open balances."/><div className="btnRow"><button className="secondary" onClick={()=>ctx.setModal({type:'charge'})}><Plus size={16}/> Add Charge/Due</button><button className="primary" onClick={()=>ctx.setModal({type:'payment'})}><HandCoins size={16}/> Record Payment</button></div></div><div className="kpiGrid"><Kpi label="Total Outstanding" value={money(outstanding)} helper="Open balances from charges"/><Kpi label="Settled Today" value={money(paidToday)} helper="Payments recorded today"/><Kpi label="Total Collected" value={money(sum(ctx.data.payments,'amount'))}/><Kpi label="Open Dues" value={charges.filter(c=>Number(c.balance)>0).length}/></div><Card title="Payment Due Roster" action={<button className="ghost" onClick={()=>csvDownload('payment_due_roster.csv',charges)}>Export</button>}><ChargesTable rows={charges} ctx={ctx}/></Card><Card title="Payment Records"><PaymentsTable rows={payments} ctx={ctx}/></Card></section>; }
function Expenses({ctx}){ const rows=filterRows(ctx.data.expenses,ctx.query,['category','vendor','camp_name','invoice_no','status']); return <section><div className="heroTitle"><Title title="Expense Management" sub="Log expense transactions and upload invoices for camp operations."/><button className="primary" onClick={()=>ctx.setModal({type:'expense'})}><Plus size={16}/> Log Expense</button></div><div className="kpiGrid"><Kpi label="Total Expenses" value={money(sum(rows,'amount'))}/><Kpi label="Utilities" value={money(sum(rows.filter(e=>['DEWA','Gas','Utilities'].includes(e.category)),'amount'))}/><Kpi label="Maintenance" value={money(sum(rows.filter(e=>e.category==='Maintenance'),'amount'))}/><Kpi label="Transactions" value={rows.length}/></div><div className="dashGrid"><Card title="Expense Breakdown"><ExpenseBreak rows={rows}/></Card><Card title="Reports Center"><ReportCards ctx={ctx}/></Card></div><Card title="Recent Transactions"><ExpenseTable rows={rows} ctx={ctx}/></Card></section>; }
function Cheques({ctx}){ const rows=filterRows(ctx.data.cheques,ctx.query,['cheque_no','bank_name','company','tenant_name','status']); return <Directory title="Cheque Ledger" sub="Cheque inventory, deposits, clearances and bounced status." rows={rows} cols={['Cheque No.','Bank','Company / Tenant','Amount','Due Date','Status']} render={c=>[c.cheque_no,c.bank_name,c.company||c.tenant_name,money(c.amount),c.due_date,<Badge>{c.status}</Badge>]} onAdd={()=>ctx.setModal({type:'cheque'})} onEdit={c=>ctx.setModal({type:'cheque',item:c})} onDelete={c=>ctx.remove('cheques',c.id)}/>; }
function SettingsPage(){ return <section><Title title="Settings" sub="Company settings and operating preferences."/><Card title="Portal Details"><div className="settingsGrid"><Field label="Portal Name"><input defaultValue="Sarab Al Madina's Portal"/></Field><Field label="Currency"><input defaultValue="AED"/></Field><Field label="Primary Email"><input defaultValue="operations@sarabalmadina.com"/></Field><button className="primary">Save Settings</button></div></Card></section>; }
function Support({ctx}){ const rows=filterRows(ctx.data.support_tickets,ctx.query,['subject','priority','status']); return <section><Title title="Support" sub="Create and track internal support requests."/><Card title="Create Support Ticket"><TicketForm ctx={ctx}/></Card><Directory title="Support Queue" rows={rows} cols={['Subject','Priority','Status','Created']} render={t=>[<b>{t.subject}</b>,<Badge>{t.priority}</Badge>,<Badge>{t.status}</Badge>,new Date(t.created_at).toLocaleDateString()]} onAdd={()=>ctx.setModal({type:'ticket'})} onEdit={t=>ctx.setModal({type:'ticket',item:t})} onDelete={t=>ctx.remove('support_tickets',t.id)}/></section>; }

function Directory({title,sub,rows,cols,render,onAdd,onEdit,onDelete,onView}){ return <section><div className="heroTitle"><Title title={title} sub={sub}/><div className="btnRow"><button className="secondary" onClick={()=>csvDownload(`${title.replaceAll(' ','_').toLowerCase()}.csv`,rows)}><Download size={16}/> Export</button><button className="primary" onClick={onAdd}><Plus size={16}/> Add New</button></div></div><Card>{!rows.length?<Empty title="No records yet" text="Use Add New or Import CSV to populate this module." action={onAdd}/>:<table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{render(r).map((c,i)=><td key={i}>{c||'—'}</td>)}<td className="rowActions">{onView&&<button title="View" onClick={()=>onView(r)}><Eye size={16}/></button>}<button title="Edit" onClick={()=>onEdit(r)}><Edit3 size={16}/></button><button title="Delete" onClick={()=>onDelete(r)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>}</Card></section>; }
function Table({cols,rows}){ return <table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c||'—'}</td>)}</tr>)}</tbody></table>; }
function Empty({title,text,action}){ return <div className="empty"><b>{title}</b><span>{text}</span>{action&&<button className="primary" onClick={action}><Plus size={16}/> Add Record</button>}</div>; }
function ChargesTable({rows,ctx}){ if(!rows.length) return <Empty title="No charges or dues yet" text="Add rent, WiFi, or other charges to create the payment due roster." action={()=>ctx.setModal({type:'charge'})}/>; return <table><thead><tr><th>Tenant</th><th>Company</th><th>Room/Camp</th><th>Charge</th><th>Due</th><th>Paid</th><th>Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.tenant_name}</b></td><td>{r.company}</td><td>{r.room} / {r.camp_name}</td><td>{r.charge_type}<br/><small>{r.period}</small></td><td>{money(r.amount_due)}</td><td className="success">{money(r.amount_paid)}</td><td className={Number(r.balance)>0?'danger':''}>{money(r.balance)}</td><td><Badge>{r.status}</Badge></td><td className="rowActions"><button className="primary small" onClick={()=>ctx.setModal({type:'payment',charge:r})}>Record Payment</button><button onClick={()=>ctx.setModal({type:'charge',item:r})}><Edit3 size={16}/></button><button onClick={()=>ctx.remove('charges',r.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>; }
function PaymentsTable({rows,ctx}){ if(!rows.length) return <Empty title="No payments recorded yet" text="Record a payment to generate receipts and collection totals."/>; return <table><thead><tr><th>Date</th><th>Tenant</th><th>Company</th><th>Amount</th><th>Method</th><th>Receipt</th><th>Actions</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{p.payment_date}</td><td>{p.tenant_name}</td><td>{p.company}</td><td>{money(p.amount)}</td><td>{p.method}</td><td>{p.receipt_no}</td><td className="rowActions"><button onClick={()=>ctx.setModal({type:'receiptView',item:p})}><Eye size={16}/></button><button onClick={()=>ctx.remove('payments',p.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>; }
function ExpenseTable({rows,ctx}){ if(!rows.length) return <Empty title="No expenses logged yet" text="Log an expense or upload invoice details to populate reports." action={()=>ctx.setModal({type:'expense'})}/>; return <table><thead><tr><th>Date</th><th>Category</th><th>Vendor</th><th>Camp</th><th>Amount</th><th>Status</th><th>Invoice</th><th>Actions</th></tr></thead><tbody>{rows.map(e=><tr key={e.id}><td>{e.expense_date}</td><td><Badge>{e.category}</Badge></td><td>{e.vendor}</td><td>{e.camp_name}</td><td>{money(e.amount)}</td><td><Badge>{e.status}</Badge></td><td>{e.invoice_no||e.invoice_path||'—'}</td><td className="rowActions"><button onClick={()=>ctx.setModal({type:'expenseView',item:e})}><Eye size={16}/></button><button onClick={()=>ctx.setModal({type:'expense',item:e})}><Edit3 size={16}/></button><button onClick={()=>ctx.remove('expenses',e.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table>; }
function ExpenseBreak({rows}){ if(!rows.length) return <Empty title="No expenses logged yet" text="Log an expense to generate this breakdown."/>; const cats=[...new Set(rows.map(r=>r.category||'Other'))]; const total=sum(rows,'amount')||1; return <div className="breakdown">{cats.map((c,i)=>{const v=sum(rows.filter(r=>(r.category||'Other')===c),'amount'); return <p key={c}><i style={{background:['#006c49','#131b2e','#ba1a1a','#75859d','#4edea3'][i%5]}}/><span>{c}</span><b>{Math.round(v/total*100)}%</b></p>})}</div>; }
function ReportCards({ctx}){ return <div className="reports"><button onClick={()=>csvDownload('profit_loss.csv',ctx.data.expenses)}><FileUp/>Profit & Loss<span>Expenses and net profit</span></button><button onClick={()=>csvDownload('collection_report.csv',ctx.data.payments)}><FileUp/>Collection Report<span>Rent, WiFi, partial, unpaid</span></button><button onClick={()=>csvDownload('occupancy_trends.csv',ctx.data.tenants)}><FileUp/>Occupancy Trends<span>Camp and room utilization</span></button></div>; }

function DynamicModal({modal,ctx,close}){ const p={company:CompanyForm,contract:ContractForm,camp:CampForm,room:RoomForm,tenant:TenantForm,allocation:AllocationForm,charge:ChargeForm,payment:PaymentForm,expense:ExpenseForm,cheque:ChequeForm,ticket:TicketFormModal,tenantView:TenantView,import:ImportModal,companyView:CompanyView,contractView:ContractView,expenseView:ExpenseView,receiptView:ReceiptView}[modal.type]; if(!p) return null; const C=p; return <C ctx={ctx} close={close} item={modal.item} charge={modal.charge} page={modal.page} table={modal.table}/>; }
function SelectCompany({ctx,defaultValue,onChange}){ return <select name="company_id" defaultValue={defaultValue||''} onChange={onChange}><option value="">Select company</option>{ctx.data.companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>; }
function SelectCamp({ctx,defaultValue,onChange}){ return <select name="camp_id" defaultValue={defaultValue||''} onChange={onChange}><option value="">Select camp</option>{ctx.data.camps.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>; }
function CompanyForm({ctx,close,item}){ return <Modal title={item?'Edit Company':'Add New Company'} onClose={close} wide><form className="formGrid" onSubmit={e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const payload=Object.fromEntries(fd); payload.balance=Number(payload.balance||0); item?ctx.update('companies',item.id,payload):ctx.insert('companies',payload);}}><Field label="Company Name"><input name="name" defaultValue={item?.name} required/></Field><Field label="Trade License"><input name="trade_license" defaultValue={item?.trade_license}/></Field><Field label="Contact Name"><input name="contact_name" defaultValue={item?.contact_name}/></Field><Field label="Phone"><input name="phone" defaultValue={item?.phone}/></Field><Field label="Email"><input name="email" defaultValue={item?.email}/></Field><Field label="Status"><select name="status" defaultValue={item?.status||'Active'}><option>Active</option><option>Inactive</option><option>On Hold</option></select></Field><Field label="Opening Balance"><input name="balance" type="number" defaultValue={item?.balance||0}/></Field><button className="primary"><Save size={16}/> Save Company</button></form></Modal>; }
function CampForm({ctx,close,item}){ return <Modal title={item?'Edit Camp':'Add New Camp'} onClose={close} wide><form className="formGrid" onSubmit={e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const p=Object.fromEntries(fd); ['rooms','capacity','maintenance_count'].forEach(k=>p[k]=Number(p[k]||0)); item?ctx.update('camps',item.id,p):ctx.insert('camps',p);}}><Field label="Camp Name"><input name="name" defaultValue={item?.name} required/></Field><Field label="Location"><input name="location" defaultValue={item?.location}/></Field><Field label="Emirate"><select name="emirate" defaultValue={item?.emirate||'Dubai'}><option>Dubai</option><option>Abu Dhabi</option><option>Sharjah</option><option>Ajman</option></select></Field><Field label="Rooms"><input name="rooms" type="number" defaultValue={item?.rooms||0}/></Field><Field label="Capacity"><input name="capacity" type="number" defaultValue={item?.capacity||0}/></Field><Field label="Maintenance Count"><input name="maintenance_count" type="number" defaultValue={item?.maintenance_count||0}/></Field><Field label="Status"><select name="status" defaultValue={item?.status||'Operational'}><option>Operational</option><option>At Capacity</option><option>Maintenance</option></select></Field><button className="primary"><Save size={16}/> Save Camp</button></form></Modal>; }
function RoomForm({ctx,close,item}){ const [campId,setCampId]=useState(item?.camp_id||''); const camp=ctx.data.camps.find(c=>c.id===campId); return <Modal title={item?'Edit Room':'Register New Room'} onClose={close} wide><form className="formGrid" onSubmit={e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const p=Object.fromEntries(fd); p.camp_id=campId||null; p.camp_name=camp?.name||item?.camp_name||''; p.capacity=Number(p.capacity||0); p.occupied=Number(p.occupied||0); item?ctx.update('rooms',item.id,p):ctx.insert('rooms',p);}}><Field label="Camp"><SelectCamp ctx={ctx} defaultValue={campId} onChange={e=>setCampId(e.target.value)}/></Field><Field label="Room No."><input name="room_no" defaultValue={item?.room_no} required/></Field><Field label="Floor"><input name="floor" defaultValue={item?.floor}/></Field><Field label="Capacity"><input name="capacity" type="number" defaultValue={item?.capacity||0}/></Field><Field label="Occupied"><input name="occupied" type="number" defaultValue={item?.occupied||0}/></Field><Field label="Status"><select name="status" defaultValue={item?.status||'Available'}><option>Available</option><option>Occupied</option><option>Maintenance</option></select></Field><button className="primary">Save Room</button></form></Modal>; }
function TenantForm({ctx,close,item}){ const [companyId,setCompanyId]=useState(item?.company_id||''); const [campId,setCampId]=useState(item?.camp_id||''); const [roomId,setRoomId]=useState(item?.room_id||''); const company=ctx.data.companies.find(c=>c.id===companyId); const camp=ctx.data.camps.find(c=>c.id===campId); const rooms=ctx.data.rooms.filter(r=>!campId||r.camp_id===campId); const room=ctx.data.rooms.find(r=>r.id===roomId); return <Modal title={item?'Edit Tenant':'Register New Tenant'} onClose={close} wide><form className="formGrid" onSubmit={e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const p=Object.fromEntries(fd); p.company_id=companyId||null; p.company=company?.name||item?.company||''; p.camp_id=campId||null; p.camp_name=camp?.name||item?.camp_name||''; p.room_id=roomId||null; p.room=room?.room_no||item?.room||''; p.docs_complete=fd.get('docs_complete')==='on'; item?ctx.update('tenants',item.id,p):ctx.insert('tenants',p);}}><Field label="Tenant Name"><input name="name" defaultValue={item?.name} required/></Field><Field label="Company"><SelectCompany ctx={ctx} defaultValue={companyId} onChange={e=>setCompanyId(e.target.value)}/></Field><Field label="Phone"><input name="phone" defaultValue={item?.phone}/></Field><Field label="Email"><input name="email" defaultValue={item?.email}/></Field><Field label="Emirates ID"><input name="emirates_id" defaultValue={item?.emirates_id}/></Field><Field label="Passport No."><input name="passport_no" defaultValue={item?.passport_no}/></Field><Field label="Camp"><SelectCamp ctx={ctx} defaultValue={campId} onChange={e=>setCampId(e.target.value)}/></Field><Field label="Room"><select value={roomId} onChange={e=>setRoomId(e.target.value)}><option value="">Select room</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.room_no} · {r.camp_name}</option>)}</select></Field><Field label="Check-in Date"><input name="check_in_date" type="date" defaultValue={item?.check_in_date||today()}/></Field><Field label="Lease End"><input name="lease_end_date" type="date" defaultValue={item?.lease_end_date}/></Field><Field label="Status"><select name="status" defaultValue={item?.status||'Active'}><option>Active</option><option>Expiring</option><option>Checked-out</option></select></Field><label className="check"><input type="checkbox" name="docs_complete" defaultChecked={item?.docs_complete}/> Documents complete</label><button className="primary">Save Tenant</button></form></Modal>; }
function ContractForm({ctx,close,item}){ const [companyId,setCompanyId]=useState(item?.company_id||''); const [campId,setCampId]=useState(item?.camp_id||''); const company=ctx.data.companies.find(c=>c.id===companyId); const camp=ctx.data.camps.find(c=>c.id===campId); return <Modal title={item?'Edit Contract':'Add / Renew Contract'} onClose={close} wide><form className="formGrid" onSubmit={e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const p=Object.fromEntries(fd); p.company_id=companyId||null; p.company=company?.name||item?.company||''; p.camp_id=campId||null; p.camp_name=camp?.name||item?.camp_name||''; p.monthly_rent=Number(p.monthly_rent||0); p.security_deposit=Number(p.security_deposit||0); item?ctx.update('contracts',item.id,p):ctx.insert('contracts',p);}}><Field label="Contract No."><input name="contract_no" defaultValue={item?.contract_no||`CNTR-${Date.now().toString().slice(-5)}`}/></Field><Field label="Company"><SelectCompany ctx={ctx} defaultValue={companyId} onChange={e=>setCompanyId(e.target.value)}/></Field><Field label="Camp"><SelectCamp ctx={ctx} defaultValue={campId} onChange={e=>setCampId(e.target.value)}/></Field><Field label="Start Date"><input name="start_date" type="date" defaultValue={item?.start_date||today()}/></Field><Field label="End Date"><input name="end_date" type="date" defaultValue={item?.end_date}/></Field><Field label="Monthly Rent"><input name="monthly_rent" type="number" defaultValue={item?.monthly_rent||0}/></Field><Field label="Security Deposit"><input name="security_deposit" type="number" defaultValue={item?.security_deposit||0}/></Field><Field label="Status"><select name="status" defaultValue={item?.status||'Active'}><option>Active</option><option>Expiring</option><option>Renewed</option><option>Closed</option></select></Field><button className="primary">Save Contract</button></form></Modal>; }
function AllocationForm({ctx,close,item}){ const [tenantId,setTenantId]=useState(item?.tenant_id||''); const [campId,setCampId]=useState(item?.camp_id||''); const [roomId,setRoomId]=useState(item?.room_id||''); const tenant=ctx.data.tenants.find(t=>t.id===tenantId); const camp=ctx.data.camps.find(c=>c.id===campId); const rooms=ctx.data.rooms.filter(r=>!campId||r.camp_id===campId); const room=ctx.data.rooms.find(r=>r.id===roomId); return <Modal title={item?'Edit Allocation':'New Room Allocation'} onClose={close} wide><form className="formGrid" onSubmit={e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const p=Object.fromEntries(fd); p.tenant_id=tenantId||null; p.tenant_name=tenant?.name||item?.tenant_name||''; p.company=tenant?.company||item?.company||''; p.camp_id=campId||null; p.camp_name=camp?.name||item?.camp_name||''; p.room_id=roomId||null; p.room=room?.room_no||item?.room||''; item?ctx.update('allocations',item.id,p):ctx.insert('allocations',p);}}><Field label="Tenant"><select value={tenantId} onChange={e=>setTenantId(e.target.value)}><option value="">Select tenant</option>{ctx.data.tenants.map(t=><option key={t.id} value={t.id}>{t.name} · {t.company}</option>)}</select></Field><Field label="Camp"><SelectCamp ctx={ctx} defaultValue={campId} onChange={e=>setCampId(e.target.value)}/></Field><Field label="Room"><select value={roomId} onChange={e=>setRoomId(e.target.value)}><option value="">Select room</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.room_no}</option>)}</select></Field><Field label="Allocation Date"><input name="allocation_date" type="date" defaultValue={item?.allocation_date||today()}/></Field><Field label="Checkout Date"><input name="checkout_date" type="date" defaultValue={item?.checkout_date}/></Field><Field label="Status"><select name="status" defaultValue={item?.status||'Active'}><option>Active</option><option>Checked-out</option><option>Transferred</option></select></Field><button className="primary">Save Allocation</button></form></Modal>; }
function ChargeForm({ctx,close,item}){ const [tenantId,setTenantId]=useState(item?.tenant_id||''); const tenant=ctx.data.tenants.find(t=>t.id===tenantId); return <Modal title={item?'Edit Charge / Due':'Add Charge / Due'} onClose={close} wide><form className="formGrid" onSubmit={e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const p=Object.fromEntries(fd); p.tenant_id=tenantId||null; p.tenant_name=tenant?.name||item?.tenant_name||''; p.company=tenant?.company||item?.company||''; p.camp_name=tenant?.camp_name||item?.camp_name||''; p.room=tenant?.room||item?.room||''; p.amount_due=Number(p.amount_due||0); p.amount_paid=Number(item?.amount_paid||0); item?ctx.update('charges',item.id,p):ctx.insert('charges',p);}}><Field label="Tenant"><select value={tenantId} onChange={e=>setTenantId(e.target.value)} required><option value="">Select tenant</option>{ctx.data.tenants.map(t=><option key={t.id} value={t.id}>{t.name} · {t.room||'No room'} · {t.company||'No company'}</option>)}</select></Field><Field label="Charge Type"><select name="charge_type" defaultValue={item?.charge_type||'Rent'}><option>Rent</option><option>WiFi</option><option>Other</option></select></Field><Field label="Period"><input name="period" defaultValue={item?.period||new Date().toLocaleString('en-US',{month:'long',year:'numeric'})}/></Field><Field label="Due Date"><input name="due_date" type="date" defaultValue={item?.due_date||today()}/></Field><Field label="Amount Due"><input name="amount_due" type="number" step="0.01" defaultValue={item?.amount_due||''} required/></Field><Field label="Status"><select name="status" defaultValue={item?.status||'Unpaid'}><option>Unpaid</option><option>Partial</option><option>Fully Paid</option></select></Field><Field label="Tenant Info"><input value={tenant?[tenant.company,tenant.camp_name,tenant.room].filter(Boolean).join(' · '):'Select tenant to populate'} readOnly/></Field><button className="primary">Save Charge</button></form></Modal>; }
function PaymentForm({ctx,close,charge}){ const [chargeId,setChargeId]=useState(charge?.id||''); const [tenantId,setTenantId]=useState(charge?.tenant_id||''); const selected=ctx.data.charges.find(c=>c.id===chargeId); const tenant=ctx.data.tenants.find(t=>t.id===(selected?.tenant_id||tenantId)); return <Modal title="Record Payment" onClose={close} wide><form className="formGrid" onSubmit={async e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const amount=Number(fd.get('amount')||0); if(amount<=0) return ctx.showToast('Enter payment amount'); const ch=ctx.data.charges.find(c=>c.id===fd.get('charge_id')); const t=ctx.data.tenants.find(x=>x.id===(ch?.tenant_id||tenantId)); const payload={charge_id:ch?.id||null,tenant_id:t?.id||null,tenant_name:ch?.tenant_name||t?.name||'',company:ch?.company||t?.company||'',payment_date:fd.get('payment_date'),method:fd.get('method'),amount,receipt_no:fd.get('receipt_no'),notes:fd.get('notes')}; const {error}=await supabase.from('payments').insert(payload); if(error) return ctx.showToast(error.message); if(ch){ const paid=Number(ch.amount_paid||0)+amount; const {error:upErr}=await supabase.from('charges').update({amount_paid:paid,status:paid>=Number(ch.amount_due||0)?'Fully Paid':'Partial',receipt_no:fd.get('receipt_no')}).eq('id',ch.id); if(upErr) return ctx.showToast(upErr.message); } await ctx.loadAll(); close(); ctx.showToast('Payment saved'); }}><Field label="Link to Charge / Due"><select name="charge_id" value={chargeId} onChange={e=>setChargeId(e.target.value)}><option value="">No linked charge / direct payment</option>{ctx.data.charges.filter(c=>Number(c.balance||0)>0).map(c=><option key={c.id} value={c.id}>{c.tenant_name} · {c.charge_type} · Balance {money(c.balance)}</option>)}</select></Field><Field label="Tenant"><select value={tenant?.id||tenantId} onChange={e=>setTenantId(e.target.value)} disabled={!!selected}><option value="">Select tenant</option>{ctx.data.tenants.map(t=><option key={t.id} value={t.id}>{t.name} · {t.company}</option>)}</select></Field><Field label="Payment Date"><input name="payment_date" type="date" defaultValue={today()}/></Field><Field label="Method"><select name="method"><option>Cash</option><option>Bank Transfer</option><option>Cheque</option><option>Card</option></select></Field><Field label="Amount Paid"><input name="amount" type="number" step="0.01" defaultValue={selected?.balance||''} required/></Field><Field label="Receipt No."><input name="receipt_no" defaultValue={`LC-${Date.now().toString().slice(-6)}`}/></Field><Field label="Tenant Info"><input value={tenant?[tenant.company,tenant.camp_name,tenant.room].filter(Boolean).join(' · '):'Select tenant to populate'} readOnly/></Field><Field label="Notes"><textarea name="notes"/></Field><button className="primary">Save Payment</button></form></Modal>; }
function ExpenseForm({ctx,close,item}){ const [campId,setCampId]=useState(item?.camp_id||''); const [file,setFile]=useState(null); const camp=ctx.data.camps.find(c=>c.id===campId); return <Modal title={item?'Edit Expense':'Add New Expense'} onClose={close} wide><form className="formGrid" onSubmit={async e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); let invoice_path=item?.invoice_path||''; if(file){ const path=`${Date.now()}_${file.name}`; const {error}=await supabase.storage.from('invoices').upload(path,file,{upsert:true}); if(error) return ctx.showToast(error.message); invoice_path=path; } const p=Object.fromEntries(fd); p.camp_id=campId||null; p.camp_name=camp?.name||item?.camp_name||''; p.amount=Number(p.amount||0); p.invoice_path=invoice_path; item?ctx.update('expenses',item.id,p):ctx.insert('expenses',p);}}><Field label="Category"><select name="category" defaultValue={item?.category||'DEWA'}><option>DEWA</option><option>Gas</option><option>Salaries</option><option>Maintenance</option><option>Landlord Rent</option><option>Other</option></select></Field><Field label="Vendor / Recipient"><input name="vendor" defaultValue={item?.vendor} required/></Field><Field label="Camp"><SelectCamp ctx={ctx} defaultValue={campId} onChange={e=>setCampId(e.target.value)}/></Field><Field label="Amount"><input name="amount" type="number" step="0.01" defaultValue={item?.amount||''} required/></Field><Field label="Expense Date"><input name="expense_date" type="date" defaultValue={item?.expense_date||today()}/></Field><Field label="Status"><select name="status" defaultValue={item?.status||'Paid'}><option>Paid</option><option>Processed</option><option>Pending</option><option>Overdue</option></select></Field><Field label="Payment Method"><select name="payment_method" defaultValue={item?.payment_method||'Cash'}><option>Cash</option><option>Bank Transfer</option><option>Cheque</option><option>Card</option></select></Field><Field label="Invoice No."><input name="invoice_no" defaultValue={item?.invoice_no}/></Field><Field label="Upload Invoice"><input type="file" onChange={e=>setFile(e.target.files?.[0])}/></Field><Field label="Notes"><textarea name="notes" defaultValue={item?.notes}/></Field><button className="primary">Save Expense</button></form></Modal>; }
function ChequeForm({ctx,close,item}){ return <Modal title={item?'Edit Cheque':'Register New Cheque'} onClose={close} wide><form className="formGrid" onSubmit={e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const p=Object.fromEntries(fd); p.amount=Number(p.amount||0); item?ctx.update('cheques',item.id,p):ctx.insert('cheques',p);}}><Field label="Cheque No."><input name="cheque_no" defaultValue={item?.cheque_no} required/></Field><Field label="Bank Name"><input name="bank_name" defaultValue={item?.bank_name}/></Field><Field label="Company"><input name="company" defaultValue={item?.company}/></Field><Field label="Tenant"><input name="tenant_name" defaultValue={item?.tenant_name}/></Field><Field label="Amount"><input name="amount" type="number" defaultValue={item?.amount||0}/></Field><Field label="Cheque Date"><input name="cheque_date" type="date" defaultValue={item?.cheque_date}/></Field><Field label="Due Date"><input name="due_date" type="date" defaultValue={item?.due_date||today()}/></Field><Field label="Status"><select name="status" defaultValue={item?.status||'In Hand'}><option>In Hand</option><option>Deposited</option><option>Cleared</option><option>Bounced</option><option>Returned</option></select></Field><Field label="Notes"><textarea name="notes" defaultValue={item?.notes}/></Field><button className="primary">Save Cheque</button></form></Modal>; }
function TicketForm({ctx}){ return <form className="supportForm" onSubmit={e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); ctx.insert('support_tickets',Object.fromEntries(fd)); e.currentTarget.reset();}}><Field label="Subject"><input name="subject" required/></Field><Field label="Priority"><select name="priority"><option>Normal</option><option>High</option><option>Urgent</option></select></Field><Field label="Description"><textarea name="description"/></Field><button className="primary">Submit Ticket</button></form>; }
function TicketFormModal({ctx,close,item}){ return <Modal title={item?'Edit Ticket':'New Support Ticket'} onClose={close} wide><form className="formGrid" onSubmit={e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const p=Object.fromEntries(fd); item?ctx.update('support_tickets',item.id,p):ctx.insert('support_tickets',p);}}><Field label="Subject"><input name="subject" defaultValue={item?.subject} required/></Field><Field label="Priority"><select name="priority" defaultValue={item?.priority||'Normal'}><option>Normal</option><option>High</option><option>Urgent</option></select></Field><Field label="Status"><select name="status" defaultValue={item?.status||'Open'}><option>Open</option><option>In Progress</option><option>Closed</option></select></Field><Field label="Description"><textarea name="description" defaultValue={item?.description}/></Field><button className="primary">Save Ticket</button></form></Modal>; }
function TenantView({ctx,close,item}){ const charges=ctx.data.charges.filter(c=>c.tenant_id===item.id||c.tenant_name===item.name); return <Modal title="Tenant Profile" onClose={close} wide><div className="profile"><h2>{item.name}</h2><p>{item.company} · {item.room} · {item.camp_name}</p><div className="kpiGrid"><Kpi label="Status" value={item.status}/><Kpi label="Balance" value={money(sum(charges,'balance'))}/><Kpi label="Documents" value={item.docs_complete?'Complete':'Pending'}/></div><ChargesTable rows={charges} ctx={ctx}/></div></Modal>; }


function ImportModal({ctx,close,page,table}){
  const [rows,setRows]=useState([]); const [name,setName]=useState('');
  const target=table||getPrimaryTable(page);
  return <Modal title={`Import ${page||''} CSV`} onClose={close} wide><div className="importBox"><p>Import writes to <b>{target||'this module'}</b>. Export first to get the correct headers, then upload the edited CSV.</p><input type="file" accept=".csv,text/csv" onChange={async e=>{ const f=e.target.files?.[0]; if(!f) return; setName(f.name); const txt=await f.text(); setRows(parseCsv(txt)); }}/>{name&&<p className="helper"><Info size={15}/> {name}: {rows.length} rows ready</p>}<div className="btnRow"><button className="secondary" onClick={()=>csvDownload(`${page||'template'}_template.csv`, getExportRows(page,ctx.data,ctx.query))}><Download size={16}/> Download Template</button><button className="primary" onClick={()=>ctx.importRecords(target,rows)} disabled={!rows.length}><Upload size={16}/> Import Rows</button></div></div></Modal>
}
function DetailGrid({rows}){ return <div className="detailGrid">{rows.map(([k,v])=><div key={k}><small>{k}</small><b>{v||'—'}</b></div>)}</div>; }
function CompanyView({ctx,close,item}){ const contracts=ctx.data.contracts.filter(c=>c.company_id===item.id||c.company===item.name); const tenants=ctx.data.tenants.filter(t=>t.company_id===item.id||t.company===item.name); return <Modal title="Company Profile" onClose={close} wide><div className="profile"><h2>{item.name}</h2><DetailGrid rows={[["Contact",item.contact_name],["Phone",item.phone],["Email",item.email],["Trade License",item.trade_license],["Status",item.status],["Balance",money(item.balance)]]}/><Card title="Related Contracts"><Table cols={["Contract","Camp","Monthly Rent","Status"]} rows={contracts.map(c=>[c.contract_no,c.camp_name,money(c.monthly_rent),c.status])}/></Card><Card title="Related Tenants"><Table cols={["Tenant","Room","Camp","Status"]} rows={tenants.map(t=>[t.name,t.room,t.camp_name,t.status])}/></Card></div></Modal>; }
function ContractView({ctx,close,item}){ return <Modal title="Contract Details" onClose={close} wide><div className="profile"><h2>{item.contract_no||'Contract'}</h2><DetailGrid rows={[["Company",item.company],["Camp",item.camp_name],["Start",item.start_date],["End",item.end_date],["Monthly Rent",money(item.monthly_rent)],["Security Deposit",money(item.security_deposit)],["Status",item.status]]}/></div></Modal>; }
function ExpenseView({ctx,close,item}){ return <Modal title="Expense Details" onClose={close} wide><div className="profile"><h2>{item.vendor}</h2><DetailGrid rows={[["Category",item.category],["Camp",item.camp_name],["Date",item.expense_date],["Amount",money(item.amount)],["Status",item.status],["Method",item.payment_method],["Invoice",item.invoice_no||item.invoice_path],["Notes",item.notes]]}/></div></Modal>; }
function ReceiptView({ctx,close,item}){ return <Modal title="Rent Receipt" onClose={close} wide><div className="receipt"><h2>LaborConnect Receipt</h2><DetailGrid rows={[["Receipt No.",item.receipt_no],["Tenant",item.tenant_name],["Company",item.company],["Date",item.payment_date],["Amount",money(item.amount)],["Method",item.method],["Notes",item.notes]]}/><button className="primary" onClick={()=>window.print()}><Printer size={16}/> Print Receipt</button></div></Modal>; }

createRoot(document.getElementById('root')).render(<App/>);
